<a href="https://colab.research.google.com/github/VielkaEncarnacion/DataAnalytics/blob/main/Python-Unit3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np #as help create an alias so its easy to call and work wirh the package

-ndim- number of dimensions

-shape- the total number of columns and rows in an array (Columns, rows)

-size- number of elements in the array

-dtype-dtatype of the object- unicode with 7

In [49]:
np_city = np. array(['NYC','LA','Houston','Miami', 'SFO'])
#np_city.ndim
#np_city.shape
#np_city.size
np_city.dtype #number of characters in the larger city name U-unit(characters)

dtype('<U7')

In [19]:
import numpy as np

np_city_with_state = np.array([['NYC','LA','Houston','Miami'], ['NY', 'CA','TX','FL']])
np_city_with_state.ndim
np_city_with_state.shape
#np_city_with_state.size
#np_city_with_state.dtype

(2, 4)

In [ ]:
#Arrays 
#Ordered index starts at 0, just like lists
#Values are summed at the index level

In [20]:
first_trial_cyclist = [10,15,17,26]
second_trial_cyclist = [12,11,21,24]

np_ftc = np.array(first_trial_cyclist)
np_stc = np.array(second_trial_cyclist)

np_ftc + np_stc

array([22, 26, 38, 50])

In [42]:
#Professor Example Version 
first_trial_cyclist = [10,15,17,26]
second_trial_cyclist = [12,11,21,24]
cyclist_time = np.array([[10,15,17,26],[12,11,21,24]]) #array0 #arrray1
ftc_time = cyclist_time[0]
ftc_times = cyclist_time[0,0]
stc_time = cyclist_time[1]
stc_times = cyclist_time[1,0]
print(ftc_time)
print(ftc_times)
print(stc_time)
print(stc_times)

[10 15 17 26]
10
[12 11 21 24]
12


In [40]:
#Two dimensional array tuple-ordered list

first_trial_cyclist = [10,15,17,26]
second_trial_cyclist = [12,11,21,24]
cyclist_time = np.array([[10,15,17,26],[12,11,21,24]]) #array0 #arrray1
ftc_time = cyclist_time[0]
print(ftc_time)

ftc_times = cyclist_time[0,0] #array and (element) location in the array
print(ftc_times)

stc_time = cyclist_time[1]
print(stc_time)

stc_times = cyclist_time[1,0]
print(stc_times)





[10 15 17 26]
10
[12 11 21 24]
12


In [47]:
#Boolean Arrays: use criteria or set condition to select values

test_score = np.array([[81,72,57,63],[54,61,87,45]])
passing_score = test_score >80 
passing_score
test_score[passing_score]

array([81, 87])

In [53]:
#Copy & view- is a shallow copy

NYC_Borough = np.array(['Manhattan', 'Queens', 'Staten Island','Bronx']) #original dataset
NYC_Borough

Boroughs_NYC = NYC_Borough
Boroughs_in_NYC = Boroughs_NYC.view()
Boroughs_in_NYC

#Boroughs in NYC is NYC_Borough

NYC_Borough is Boroughs_NYC
len(Boroughs_in_NYC)
Boroughs_in_NYC[3]

'Bronx'

In [57]:
#Universal Function: 

np_sqrt = np.sqrt([2,4,9,16])
np_sqrt

from numpy import pi
#np.cos(0)
#np.sin(pi/2)
#np.cos(pi)
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])
#np.exp([0,1,5])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [60]:
#Broadcasting: Arithmetic operations between arrays of different shapes- select smaller array over bigger array

array_a = np.array([2,3,5,9])
array_b = np.array([0.3,0.3,0.3,0.3])

#multiply
array_a * array_b

#variable with scalar view
#scalar_c = 0.3
#array_a * scalar_c

array([0.6, 0.9, 1.5, 2.7])

In [62]:
#Transpose: change rows into column- np.linalg.inverse of a matrix- works only on a square matrix

inverse_array = np.array([[10,20],[15,25]])
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [63]:
#Trace: Sum of diagonal elements

trace_array = np.array([[10,20],[22,31]])
np.trace(trace_array)



41